SET(KWS_HEADERS
    kws.h
    kws_dnn.h
    kws_ds_cnn.h
    )

SET(KWS_SRC_FILES
    kws.cpp
    kws_dnn.cpp
    kws_ds_cnn.cpp
    )

SET(MFCC_HEADERS
    mfcc.h
    )

SET(MFCC_SRC_FILES
    mfcc.cpp
    )

SET(NN_HEADERS
    nn.h
    dnn.h
    dnn_weights.h
    ds_cnn.h
    ds_cnn_weights.h
    )

SET(NN_SRC_FILES
    nn.cpp
    dnn.cpp
    ds_cnn.cpp
    )

SET(LOCAL_NN_HEADERS
    local_NN.h
    )

SET(LOCAL_NN_SRC_FILES
    arm_avepool_q7_HWC_nonsquare.c
    )

SET(KWS_F413ZH_HEADERS
    kws_f413zh.h
    )

SET(KWS_F413ZH_SRC_FILES
    kws_f413zh.cpp
    )

FOREACH(HEADER ${KWS_HEADERS})
    STRING(MAKE_C_IDENTIFIER "${HEADER}" HEADER_CLEAN)
    SET(KWS_${HEADER_CLEAN}_DIR KWS_INCLUDE_DIR-NOTFOUND)
    FIND_PATH(KWS_${HEADER_CLEAN}_DIR ${HEADER}
        PATH_SUFFIXES KWS_DNN KWS_DS_CNN
        HINTS ${KWS_DIR}/Deployment/Source/KWS
        REQUIRED
        CMAKE_FIND_ROOT_PATH_BOTH
        )
    LIST(APPEND KWS_INC_DIRS ${KWS_${HEADER_CLEAN}_DIR})
ENDFOREACH()

FOREACH(SRC ${KWS_SRC_FILES})
    STRING(MAKE_C_IDENTIFIER "${SRC}" SRC_CLEAN)
    SET(KWS_${SRC_CLEAN}_FILE KWS_SRC_FILE-NOTFOUND)
    FIND_FILE(KWS_${SRC_CLEAN}_FILE ${SRC}
        PATH_SUFFIXES KWS_DNN KWS_DS_CNN
        HINTS ${KWS_DIR}/Deployment/Source/KWS
        CMAKE_FIND_ROOT_PATH_BOTH
        )
    LIST(APPEND KWS_SRCS ${KWS_${SRC_CLEAN}_FILE})
ENDFOREACH()

FOREACH(HEADER ${MFCC_HEADERS})
    STRING(MAKE_C_IDENTIFIER "${HEADER}" HEADER_CLEAN)
    SET(MFCC_${HEADER_CLEAN}_DIR MFCC_INCLUDE_DIR-NOTFOUND)
    FIND_PATH(MFCC_${HEADER_CLEAN}_DIR ${HEADER}
        NAME ${HEADER}
        HINTS ${KWS_DIR}/Deployment/Source/MFCC
        CMAKE_FIND_ROOT_PATH_BOTH
        )
      LIST(APPEND MFCC_INC_DIRS ${MFCC_${HEADER_CLEAN}_DIR})
ENDFOREACH()

FOREACH(SRC ${MFCC_SRC_FILES})
    STRING(MAKE_C_IDENTIFIER "${SRC}" SRC_CLEAN)
    SET(MFCC_${SRC_CLEAN}_FILE MFCC_SRC_FILE-NOTFOUND)
    FIND_FILE(MFCC_${SRC_CLEAN}_FILE ${SRC}
        HINTS ${KWS_DIR}/Deployment/Source/MFCC
        CMAKE_FIND_ROOT_PATH_BOTH
        )
      LIST(APPEND MFCC_SRCS ${MFCC_${SRC_CLEAN}_FILE})
ENDFOREACH()

FOREACH(HEADER ${NN_HEADERS})
    STRING(MAKE_C_IDENTIFIER "${HEADER}" HEADER_CLEAN)
    SET(NN_${HEADER_CLEAN}_DIR NN_INCLUDE_DIR-NOTFOUND)
    FIND_PATH(NN_${HEADER_CLEAN}_DIR ${HEADER}
        PATH_SUFFIXES DNN DS_CNN
        HINTS ${KWS_DIR}/Deployment/Source/NN
        CMAKE_FIND_ROOT_PATH_BOTH
        )
    LIST(APPEND NN_INC_DIRS ${NN_${HEADER_CLEAN}_DIR})
ENDFOREACH()

FOREACH(SRC ${NN_SRC_FILES})
    STRING(MAKE_C_IDENTIFIER "${SRC}" SRC_CLEAN)
    SET(NN_${SRC_CLEAN}_FILE NN_SRC_FILE-NOTFOUND)
    FIND_FILE(NN_${SRC_CLEAN}_FILE ${SRC}
        HINTS ${KWS_DIR}/Deployment/Source/NN ${KWS_DIR}/Deployment/Source/NN/DNN ${KWS_DIR}/Deployment/Source/NN/DS_CNN
        CMAKE_FIND_ROOT_PATH_BOTH
        )
   LIST(APPEND NN_SRCS ${NN_${SRC_CLEAN}_FILE})
ENDFOREACH()

FOREACH(HEADER ${LOCAL_NN_HEADERS})
    STRING(MAKE_C_IDENTIFIER "${HEADER}" HEADER_CLEAN)
    SET(LOCAL_NN_${HEADER_CLEAN}_DIR LOCAL_NN_INCLUDE_DIR-NOTFOUND)
    FIND_PATH(LOCAL_NN_${HEADER_CLEAN}_DIR ${HEADER}
        HINTS ${KWS_DIR}/Deployment/Source/local_NN
        CMAKE_FIND_ROOT_PATH_BOTH
        )
    LIST(APPEND LOCAL_NN_INC_DIRS ${LOCAL_NN_${HEADER_CLEAN}_DIR})
ENDFOREACH()

FOREACH(SRC ${LOCAL_NN_SRC_FILES})
    STRING(MAKE_C_IDENTIFIER "${SRC}" SRC_CLEAN)
    SET(LOCAL_NN_${SRC_CLEAN}_FILE LOCAL_NN_SRC_FILE-NOTFOUND)
    FIND_FILE(LOCAL_NN_${SRC_CLEAN}_FILE ${SRC}
      HINTS ${KWS_DIR}/Deployment/Source/local_NN
        CMAKE_FIND_ROOT_PATH_BOTH
        )
      LIST(APPEND LOCAL_NN_SRCS ${LOCAL_NN_${SRC_CLEAN}_FILE})
ENDFOREACH()

FOREACH(HEADER ${KWS_F413ZH_HEADERS})
    STRING(MAKE_C_IDENTIFIER "${HEADER}" HEADER_CLEAN)
    SET(KWS_F413ZH_${HEADER_CLEAN}_DIR KWS_F413ZH_INCLUDE_DIR-NOTFOUND)
    FIND_PATH(KWS_F413ZH_${HEADER_CLEAN}_DIR ${HEADER}
        HINTS ${KWS_DIR}/Deployment/Source/KWS_F413ZH
        CMAKE_FIND_ROOT_PATH_BOTH
        )
    LIST(APPEND KWS_F413ZH_INC_DIRS ${KWS_F413ZH_${HEADER_CLEAN}_DIR})
ENDFOREACH()

FOREACH(SRC ${KWS_F413ZH_SRC_FILES})
    STRING(MAKE_C_IDENTIFIER "${SRC}" SRC_CLEAN)
    SET(KWS_F413ZH_${SRC_CLEAN}_FILE KWS_F413ZH_SRC_FILE-NOTFOUND)
    FIND_FILE(KWS_F413ZH_${SRC_CLEAN}_FILE ${SRC}
      HINTS ${KWS_DIR}/Deployment/Source/KWS_F413ZH
        CMAKE_FIND_ROOT_PATH_BOTH
        )
      LIST(APPEND KWS_F413ZH_SRCS ${KWS_F413ZH_${SRC_CLEAN}_FILE})
ENDFOREACH()

SET(KWS_INCLUDE_DIRS
    ${KWS_INC_DIRS}
    ${MFCC_INC_DIRS}
    ${NN_INC_DIRS}
    ${LOCAL_NN_INC_DIRS}
    ${KWS_F413ZH_INC_DIRS}
    )

SET(KWS_SOURCES
    ${KWS_SRCS}
    ${MFCC_SRCS}
    ${NN_SRCS}
    ${LOCAL_NN_SRCS}
    ${KWS_F413ZH_SRCS}
    )

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(KWS DEFAULT_MSG KWS_INCLUDE_DIRS KWS_SOURCES)
