set(TFLM_BOARDS
    disco_f413zh
    disco_f746ng
    disco_f769ni
)

set(TFLM_EXAMPLES
    hello_world
    micro_speech
    mnist
)

set(TFLM_COMMON_HEADERS
    main_functions.h
)
list(LENGTH TFLM_BOARD TFLM_BOARD_COUNT)
IF(${TFLM_BOARD_COUNT} EQUAL 1)
  list(FIND TFLM_BOARDS ${TFLM_BOARD} TFLM_BOARD_INDEX)
  IF(${TFLM_BOARD_INDEX} LESS 0)
	  MESSAGE(FATAL_ERROR "Unknown TFLM board: ${TFLM_BOARD}. Available boards: ${TFLM_BOARDS}")
  ELSE()
    MESSAGE("TFLM Board: ${TFLM_BOARD}")
  ENDIF()
ELSE()
 MESSAGE(FATAL_ERROR "Please use TFLM_BOARD to specify exactly one of the following supported boards: ${TFLM_BOARDS}")
ENDIF()

IF(NOT TFLMExamples_FIND_COMPONENTS)
  MESSAGE(FATAL_ERROR "No TFLMExamples component selected, chose one of: ${TFLM_EXAMPLES}")
ENDIF()
list(LENGTH TFLMExamples_FIND_COMPONENTS TFLM_EXAMPLE_COUNT)
IF(${TFLM_EXAMPLE_COUNT} EQUAL 1)
  set(TFLM_EXAMPLE ${TFLMExamples_FIND_COMPONENTS})
  list(FIND TFLM_EXAMPLES ${TFLM_EXAMPLE} TFLM_EXAMPLE_INDEX)
  IF(${TFLM_EXAMPLE_INDEX} LESS 0)
    MESSAGE(FATAL_ERROR "Unknown TFLM Example: ${TFLM_EXAMPLE}. Available examples: ${TFLM_EXAMPLES}")
  ELSE()
    MESSAGE("TFLM Example: ${TFLM_EXAMPLE}")
  ENDIF()
ELSE()
  #FIND_PACKAGE(TFLMExamples COMPONENTS micro_speech REQUIRED)
  MESSAGE(FATAL_ERROR "Please use TFLM_EXAMPLE to specify exactly one of the following supported examples: ${TFLM_EXAMPLES}")
ENDIF()

UNSET(TFLM_EXAMPLE_DIR CACHE)
FIND_PATH(TFLM_EXAMPLE_DIR ${TFLM_COMMON_HEADERS}
  HINTS ${PROJECT_SOURCE_DIR}/Src/${TFLM_EXAMPLE}
	CMAKE_FIND_ROOT_PATH_BOTH
	)

message(STATUS "TFLM_EXAMPLE=${TFLM_EXAMPLE} TFLM_EXAMPLE_DIR=${TFLM_EXAMPLE_DIR}")

file(GLOB_RECURSE EXAMPLE_SOURCES
  "${TFLM_EXAMPLE_DIR}/*.cc"
  )

set(TFLM_BOARDS_TO_REMOVE
)
FOREACH(cmp ${TFLM_BOARDS})
  IF(NOT (${cmp} STREQUAL ${TFLM_BOARD}))
    LIST(APPEND TFLM_BOARDS_TO_REMOVE ${cmp})
  ENDIF()
ENDFOREACH() 

FOREACH(path ${EXAMPLE_SOURCES})
  FOREACH(cmp ${TFLM_BOARDS_TO_REMOVE})
    STRING(FIND ${path} ${cmp} result)
    IF(${result} GREATER 0)
      LIST(REMOVE_ITEM EXAMPLE_SOURCES ${path})
    ENDIF()
  ENDFOREACH() 
ENDFOREACH() 

set(TFLMExamples_INCLUDE_DIR
  ${TFLM_EXAMPLE_DIR}
  )

set(TFLMExamples_SOURCES
  ${EXAMPLE_SOURCES}
  )

message(STATUS "TFLMExamples Sources: ${TFLMExamples_SOURCES}")
MESSAGE(STATUS "TFLMExamples Include Dirs: ${TFLMExamples_INCLUDE_DIR}")

add_definitions(-DTFLM_EXAMPLE="${TFLM_EXAMPLE}" -DTFLM_BOARD="${TFLM_BOARD}")

IF("${TFLM_EXAMPLE}" STREQUAL "hello_world")
  add_definitions(-DHELLO_WORLD_EXAMPLE)
ELSEIF("${TFLM_EXAMPLE}" STREQUAL "micro_speech")
  add_definitions(-DMICRO_SPEECH_EXAMPLE)
  add_definitions(-DFIXED_POINT=16)
  IF(${FAKE_MIC})
    add_definitions(-DFAKE_MIC -DTFLM_FILE_EXT="*.wav")
  ENDIF()
ELSEIF("${TFLM_EXAMPLE}" STREQUAL "mnist")
  add_definitions(-DMNIST_EXAMPLE)
  IF(${FAKE_TOUCH})
    add_definitions(-DFAKE_TOUCH -DTFLM_FILE_EXT="*.bmp")
  ENDIF()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(TFLMExamples DEFAULT_MSG TFLMExamples_INCLUDE_DIR TFLMExamples_SOURCES)
